JANOARG Chart Format
github.com/FFF40/JANOARG

[VERSION]
1

[METADATA]
Index: -1
Name: Test Difficulty
Charter: dudududucat
Level: ??
Constant: 0

[CAMERA]
Pivot: 0 10 0
Rotation: 30 0 0
Distance: 10

[GROUPS]

[PALLETE]
Background: 1 1 1 1
Interface: 0 0 0 1
+ LaneStyle 0 0 0 0.5019608 0 0 0 1
+ HitStyle 0 0 0 1 0 0 0 1 0 0 1 1

[OBJECTS]
+ Lane 0 -4 6 0 0 0 0
  + LaneStep -4b -6 0 Linear Linear 6 0 Linear Linear 1
  + LaneStep 108b1/4 -6 0 Linear Linear 6 0 Linear Linear 1
  + Hit Catch 0b 0 1 0 N 0
  + Hit Normal 0b1/2 0 1 0 N 0
  + Hit Catch 2b 0 1 0 N 0
  + Hit Normal 2b1/2 0 1 0 N 0
  + Hit Catch 4b 0 1 0 N 0
  + Hit Normal 4b1/2 0 1 0 N 0
  + Hit Catch 6b 0 1 0 N 0
  + Hit Normal 6b1/2 0 1 0 N 0
  + Hit Catch 8b 0 1 0 N 0
  + Hit Normal 8b1/2 0 1 0 N 0
  + Hit Catch 10b 0 1 0 N 0
  + Hit Normal 10b1/2 0 1 0 N 0
  + Hit Catch 12b 0 1 0 N 0
  + Hit Normal 12b1/2 0 1 0 N 0
  + Hit Catch 14b 0 1 0 N 0
  + Hit Normal 14b1/2 0 1 0 N 0
  + Hit Normal 16b -1 3 0 N 0
  + Hit Normal 16b1/4 -1 3 0 N 0
  + Hit Normal 16b1/2 -1 3 0 N 0
  + Hit Normal 16b1/2 -1 3 0 N 0
  + Hit Normal 16b3/4 -1 3 0 N 0
  + Hit Normal 16b3/4 -1 3 0 N 0
  + Hit Normal 17b -1 3 0 N 0
  + Hit Normal 17b1/4 -1 3 0 N 0
  + Hit Normal 17b1/2 -1 3 0 N 0
  + Hit Normal 17b1/2 -1 3 0 N 0
  + Hit Normal 17b3/4 -1 3 0 N 0
  + Hit Normal 17b3/4 -1 3 0 N 0
  + Hit Normal 18b -1 3 0 N 0
  + Hit Normal 18b1/4 -1 3 0 N 0
  + Hit Normal 18b1/2 -1 3 0 N 0
  + Hit Normal 18b1/2 -1 3 0 N 0
  + Hit Normal 18b3/4 -1 3 0 N 0
  + Hit Normal 18b3/4 -1 3 0 N 0
  + Hit Normal 19b -1 3 0 N 0
  + Hit Normal 19b1/4 -1 3 0 N 0
  + Hit Normal 19b1/2 -1 3 0 N 0
  + Hit Normal 19b1/2 -1 3 0 N 0
  + Hit Normal 19b3/4 -1 3 0 N 0
  + Hit Normal 19b3/4 -1 3 0 N 0